plugins {
    id 'com.android.application'
}

android {
    namespace 'xyz.zip8919.app.aichat'
    compileSdk 34

    signingConfigs {
        release {
            storeFile file("keystore/mc.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD") ?: project.findProperty("keystorePassword") ?: ""
            keyAlias System.getenv("KEY_ALIAS") ?: project.findProperty("keyAlias") ?: ""
            keyPassword System.getenv("KEYSTORE_PASSWORD") ?: project.findProperty("keystorePassword") ?: ""
        }
    }

    defaultConfig {
        applicationId 'xyz.zip8919.app.aichat'
        minSdk 18
        targetSdk 18
        versionCode 8
        versionName "1.2.4"

        buildConfigField "String", "DEEPSEEK_KEY", "\"${project.findProperty('deepseekKey') ?: 'sk-xxx'}\""
        buildConfigField "String", "SILICONFLOW_KEY", "\"${project.findProperty('siliconflowKey') ?: 'sk-xxx'}\""
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError false
    }

    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    implementation 'ru.noties:jlatexmath-android:0.2.0'
    implementation 'org.commonmark:commonmark:0.21.0'
    implementation 'org.commonmark:commonmark-ext-gfm-strikethrough:0.21.0'
    implementation 'org.commonmark:commonmark-ext-gfm-tables:0.21.0'
}
